### ISSUE TITLE
Malformed input data, multiple clonotype_ids are associated with the same cell barcode

### ISSUE THREAD

**Issue by Ahmedalaraby20** [rnabioco/djvdj#130] opened 2023-03-30 14:29 UTC
Hey, 
Is there any way for me to filter cells that have multiple clonotypes? cause otherwise the impotvdj does not work and I can't analysis my data.

**Comment by sheridar** [comment] 2023-03-30 14:52
Hmm I don't think I've encountered this issue before, I think the best way to handle this is to automatically remove these cells and print a warning. This should be easy to fix, @Ahmedalaraby20 would you be okay with sending me your filtered_contig_annotations.csv file from the cellranger output directory

**Comment by sheridar** [comment] 2023-03-30 17:14
This is fixed in 22fdbfb32137b76a38831ed1b86fa2987ac982d8. Before merging, I would like to check more on why you have a cell barcode with multiple clonotype IDs from cellranger (and double check that this is in fact the issue with your file)

**Comment by sheridar** [comment] 2023-03-30 21:35
Hey Ahmed, just took a quick look at your file. The issue is that the string, "No", is included in your file to indicate a missing value (e.g. often the d_gene is not identified and will be missing for some cells) 

Did you generate this file with `cellranger vdj`, and what version of `cellranger` did you use? Was this file modified by hand after running `cellranger`? Usually when a cell is missing a value, it is recorded by `cellranger` as "NA" or left blank. The presence of the string "No" as a clonotype_id is what caused the error you saw.

**Comment by Ahmedalaraby20** [comment] 2023-03-31 20:41
The file was generated via cellranger count and I replaced NAs with "No", 
I removed the cells with no in the clonotype_id column and it worked fine thanks a lot.

**Comment by sheridar** [comment] 2023-03-31 22:19
Glad this is resolved, in the future I would avoid modifying the filtered_contig_annotations.csv file, since this isn't necessary for using djvdj. I'm closing this, feel free to open another issue if you run into any other problems, good luck!

**Closed** 2023-03-31 22:19 UTC
